### ISSUE TITLE
CUDA error even when using cpu yaml

### ISSUE THREAD

**Issue by Omar-Nour** [PRBonn/PIN_SLAM#10]
Hello and thank you for your great work.

I was trying to use this command `python pin_slam.py ./config/lidar_slam/run_demo_cpu.yaml` to run the initial test but i get this error:
```Traceback (most recent call last):
  File "pin_slam.py", line 380, in <module>
    run_pin_slam()
  File "pin_slam.py", line 103, in run_pin_slam
    T0 = get_time()
  File "/home/omar-nour/catkin_ws/src/PIN_SLAM/utils/tools.py", line 273, in get_time
    torch.cuda.synchronize()
  File "/home/omar-nour/miniconda3/envs/pin/lib/python3.8/site-packages/torch/cuda/__init__.py", line 799, in synchronize
    _lazy_init()
  File "/home/omar-nour/miniconda3/envs/pin/lib/python3.8/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

I am trying to run PIN-SLAM on Ubuntu 20.04 Virtual Machine (Virtual Box) with ROS Noetic

**Comment by YuePanEdward** [comment]
Thanks for your interest in our work and the report of this bug.
This is due to the blind `torch.cuda.synchronize()` call in `get_time()` when there's no cuda devices (CPU only).
Now you can pull the latest version and try it again.
