### ISSUE TITLE
Clarify dependencies / requirements

### ISSUE THREAD

**Issue by jhpauls** [PRBonn/PIN_SLAM#21]
Hi,

First of all, thanks for the great work and for open-sourcing it! I am really curious about trying it out.

When following the installation instructions on Ubuntu 20.04, I get the following error:
```
Traceback (most recent call last):
  File "pin_slam.py", line 11, in <module>
    import open3d as o3d
  File "/home/jhpauls/anaconda3/envs/pin_slam/lib/python3.8/site-packages/open3d/__init__.py", line 146, in <module>
    import open3d.ml
  File "/home/jhpauls/anaconda3/envs/pin_slam/lib/python3.8/site-packages/open3d/ml/__init__.py", line 16, in <module>
    from . import datasets
  File "/home/jhpauls/anaconda3/envs/pin_slam/lib/python3.8/site-packages/open3d/ml/datasets.py", line 15, in <module>
    from open3d._ml3d.datasets import *
  File "/home/jhpauls/anaconda3/envs/pin_slam/lib/python3.8/site-packages/open3d/_ml3d/datasets/__init__.py", line 3, in <module>
    from .semantickitti import SemanticKITTI
  File "/home/jhpauls/anaconda3/envs/pin_slam/lib/python3.8/site-packages/open3d/_ml3d/datasets/semantickitti.py", line 6, in <module>
    from sklearn.neighbors import KDTree
  File "/home/jhpauls/anaconda3/envs/pin_slam/lib/python3.8/site-packages/sklearn/__init__.py", line 83, in <module>
    from .base import clone
  File "/home/jhpauls/anaconda3/envs/pin_slam/lib/python3.8/site-packages/sklearn/base.py", line 19, in <module>
    from .utils import _IS_32BIT
  File "/home/jhpauls/anaconda3/envs/pin_slam/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 15, in <module>
    from scipy.sparse import issparse
  File "/home/jhpauls/.local/lib/python3.8/site-packages/scipy/__init__.py", line 70, in <module>
    from ._lib.deprecation import _deprecated
ModuleNotFoundError: No module named 'scipy._lib'
```

I suspect the default versions of e.g. scipy and/or sklearn have changed. 

Could you export the exact dependencies in a requirements / environment file or specify them in the README?

Thanks a lot!

**Comment by YuePanEdward** [comment]
Thanks for reporting. I will add a requirement/environment file upon the next update.
